const FPS = 60;

const GAME_WORLD_WIDTH = 960;
const GAME_WORLD_HEIGHT = 540;

const PLAYER_STARTING_X = 50;
const PLAYER_STARTING_Y = GAME_WORLD_HEIGHT / 2;
const PLAYER_SPEED = 3;
const PLAYER_WIDTH = 30;
const PLAYER_HEIGHT = 30;

const OBSTCALE_SPEED = 1;
const OBSTCALE_GENERATION_SPEED = 1000;
const OBSTCALE_STARTING_X = 300;
const OBSTCALE_WIDTH = 10;
const OBSTCALE_MAX_HEIGHT = (GAME_WORLD_HEIGHT - PLAYER_HEIGHT) / 2;
const OBSTCALE_MIN_HEIGHT = 20;
const OBSTCALE_VERTICAL_INCREMENT = 3;
const LOWER_OBSTCALE_STARTING_POINT = GAME_WORLD_HEIGHT - OBSTCALE_MAX_HEIGHT;
const HEIGHER_OBSTCALE_STARTING_POINT = 0;
const SAFE_FACTOR = 5;

const PROJECTILE_SPEED = 1;
const projectileGenerationSpeed = 2000;
const PROJECTILE_WIDTH = 50;
const PROJECTILE_HEIGHT = 30;